services:
  - type: web
    name: simulado-fruticultura
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    autoDeploy: true
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
